### ISSUE TITLE
[Suggestion] Better method chaining formatting

### ISSUE THREAD

**Issue by MatanYadaev** [matt-allan/laravel-code-style#36] opened 2020-11-03 14:08 UTC
**Is your feature request related to a problem? Please describe.**
When using method chaining, and the first method is multiline - the first method gets one nesting level down.
```php
// Before
$notification->loadMorph('owner', [
        User::class => 'profile',
        Admin::class => 'something'
    ])
    ->append('message');
// After
$notification->loadMorph('owner', [
    User::class => 'profile',
    Admin::class => 'something'
])
    ->append('message');
```

If the multiline method weren't first, it got fixed correctly:
```php
// Before
$notification->append('message')
->loadMorph('owner', [
    User::class => 'profile',
    Admin::class => 'something'
]);
// After
$notification->append('message')
    ->loadMorph('owner', [
        User::class => 'profile',
        Admin::class => 'something'
    ]);
```

**Describe the solution you'd like**
When the first chaining method is multiline, it should have the same nesting level as the rest chaining methods.
Example:
```php
$notification->loadMorph('owner', [
        User::class => 'profile',
        Admin::class => 'something'
    ])
    ->append('message');
```

**Comment by matt-allan** [comment] 2020-11-03 15:00
Hi,

This is being caused by the [`array_indentation` rule](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.16/doc/rules/whitespace/array_indentation.rst) which is provided by [PHP-CS-Fixer](https://github.com/FriendsOfPhp/PHP-CS-Fixer), not this library.

I put together a [simple, isolated example](https://gist.github.com/matt-allan/bc662b5fa4ebceadcdd8af7ed518c4e0) to illustrate your issue.

The goal of this project is to recreate the configuration being used by the Laravel framework, and since the Laravel framework uses the `array_indentation` rule, I don't think we should change this behavior.

You may be able to get the behavior you want by adding another [existing rule](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.16/doc/rules/index.rst) or writing your own.

What I usually do in this case is format the method calls like this:

```php
<?php

$notification->loadMorph('owner', [
    User::class => 'profile',
    Admin::class => 'something',
])->append('message');
```

That format works fine with the fixers and does not get reformatted. You can see a lot of examples of this style in the Laravel source code, i.e. [1](https://github.com/laravel/framework/blob/37a0abd4f3dbc51e2256296b45f8be72c8fe2196/src/Illuminate/Console/Concerns/CallsCommands.php#L82), [2](https://github.com/laravel/framework/blob/37a0abd4f3dbc51e2256296b45f8be72c8fe2196/tests/Http/HttpClientTest.php#L420), [3](https://github.com/laravel/framework/blob/37a0abd4f3dbc51e2256296b45f8be72c8fe2196/tests/Queue/DynamoDbFailedJobProviderTest.php#L63).

I'm going to close this issue but feel free to follow up if you have any questions or think this is a bug.

**Closed as completed by matt-allan** 2020-11-03 15:00 UTC
